Basic with small data set

In [2]:
import pandas as pd

dataframe is the multiple series(row/columns) object like the gmail series

In [3]:
# it take only one value in the columns
person={
    "first" : "yash",
    "last": "jain",
    "gmail": "jainy9089"
}

In [4]:
# it have one value in the columns
person={
    "first" : ["yash"],
    "last": ["jain"],
    "gmail": ["jainy9089"]
}

In [5]:
# it take multiple value in the columns
person={
    "first" : ["yash" , "riya"],
    "last": ["jain", "goyal"],
    "gmail": ["jainy9089", "riyayash"]
}

In [6]:
person["gmail"]

['jainy9089', 'riyayash']

In [7]:
# display the data in the table form
df=pd.DataFrame(person)
df

  first   last      gmail
0  yash   jain  jainy9089
1  riya  goyal   riyayash

In [21]:
print(df[["first" , "last"]])
print("\n",df.loc[:,["first" , "last"]])

  first   last
0  yash   jain
1  riya  goyal

   first   last
0  yash   jain
1  riya  goyal

In [9]:
# access colomn
print(df['gmail'],"\n")
print(df.gmail) #it access the method if it's present
type(df['gmail'])

0    jainy9089
1     riyayash
Name: gmail, dtype: object

0    jainy9089
1     riyayash
Name: gmail, dtype: object

pandas.core.series.Series

In [10]:
# access the two or more columns
df[["first","last" ]]

  first   last
0  yash   jain
1  riya  goyal

In [11]:
# show all the columns name and type of data
df.columns

Index(['first', 'last', 'gmail'], dtype='object')

iloc[]

In [12]:
# it take the index no. for the access the value of the data
# it retuen the rows information with index no. and dtype
print(df.iloc[0])
df.iloc[[0,1]]

first         yash
last          jain
gmail    jainy9089
Name: 0, dtype: object

  first   last      gmail
0  yash   jain  jainy9089
1  riya  goyal   riyayash

In [13]:
want_acces_rows =[0,1]

want_access_columns = [1,2]

df.iloc[want_acces_rows,want_access_columns]

    last      gmail
0   jain  jainy9089
1  goyal   riyayash

loc[]

In [14]:
# loc[]:- it take the both index and row/columns name
want_acces_rows =[0,1]

want_access_columns = []

df.loc[want_acces_rows,"gmail"]

0    jainy9089
1     riyayash
Name: gmail, dtype: object

In [15]:
want_acces_rows =[0,1]

want_access_columns = ["gmail","first"]

df.loc[want_acces_rows,want_access_columns]

       gmail first
0  jainy9089  yash
1   riyayash  riya

Practice on the stack overflow data set

In [16]:

da=pd.read_csv(r"C:\Users\YASH JAIN\Documents\New Folder\OneDrive\Desktop\CodeBox\python language\panda\data\survey_results_public.csv")
# treate like a simple string 
# \n,\a it disturb the file path so it a incorrect way to access the file by path
#da=pd.read_csv("C:\Users\YASH JAIN\Documents\New Folder\OneDrive\Desktop\CodeBox\python language\panda\data\survey_results_public.csv") 
da

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\YASH JAIN\\Documents\\New Folder\\OneDrive\\Desktop\\CodeBox\\python language\\panda\\data\\survey_results_public.csv'

In [ ]:

print(da.columns) #columns present in a data
print(da.shape)  #show the no. of row and columns present

Index(['ResponseId', 'MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       ...
       'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9',
       'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength', 'SurveyEase',
       'ConvertedCompYearly', 'JobSat'],
      dtype='object', length=114)
(65437, 114)

In [ ]:
# da['LearnCodeOnline'].head()

da['SOAccount'].head(10).value_counts()

SOAccount
Yes    8
No     2
Name: count, dtype: int64

In [ ]:

da.loc[[0,1],"Employment"]

0    Employed, full-time
1    Employed, full-time
Name: Employment, dtype: object

In [ ]:
# access by the indexing
da.loc[[0,1]]

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor? degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN

In [ ]:
# access with a silicing

#Note:- access also the last vale of the silicing
da.loc[0:2,"Employment"]

0    Employed, full-time
1    Employed, full-time
2    Employed, full-time
Name: Employment, dtype: object

In [ ]:
# access with a silicing

#Note:- access also the last value of the silicing
da.loc[0:2,"Employment":"Check":2]

            Employment   Check
0  Employed, full-time  Apples
1  Employed, full-time  Apples
2  Employed, full-time  Apples